base:
  seed: 42
  target: Survived

data:
  # DIRs
  input: data/init/titanic.zip
  data_dir: data
  init_dir: data/init
  unzip_dir: data/unzip
  prepared_dir: data/prepared
  featurize_dir: data/featurized
  predict_dir: predictions
  uznip_dir: unzip

  # Files
  train_name: train.csv
  test_name: test.csv
  prep_pred_name: pred.cvs
  prep_train_name: prep_train.cvs
  prep_test_name: prep_test.cvs
  trainpkl: train.pkl
  testpkl: test.pkl
  predpkl: pred.pkl
  sub_name: gender_submission.csv

featurize:
  used_cols:
  - Age
  - Fare
  - Sex
  - Pclass
  - Embarked
  cat_cols:
  - Sex
  - Embarked
  num_cols:
  - Age
  - Fare

prepare:
  split: 0.2

train:
  model_dir: models
  model: model.pkl
  n_estim: 472
  crit: gini
  max_d: 11
  min_s_s: 2
  min_s_l: 1
  n_j: -1
  seed: 42

evaluate:
  seed: 42
  n_split: 5
  reports_dir: reports
  importance: importance.png
  plots: plots.json
  scores: scores.json
  classes: classes.csv
  cvs: cross_val_score.csv
  cvs_mean: cross_val_score_mean.csv




